CREATE DATABASE VideosDB;
GO
USE VideosDB;
GO
CREATE TABLE Video(VideoId VARCHAR(50) NOT NULL PRIMARY KEY, Titulo VARCHAR(2000), Descripcion VARCHAR(MAX), ImageUrl NVARCHAR(200), VideoUrl NVARCHAR(500), Agregado DATETIME);
GO